language: java
sudo: false
script: mvn clean compile package
deploy:
  provider: azure_web_apps
  username: $AZURE_USERNAME
  password: $AZURE_PASSWORD
  site: $AZURE_SITE
  skip_cleanup: true
  on:
    branch: develop